//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.225 版自动生成。
// 
#pragma warning disable 1591

namespace Test.NTest.Real {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RealSrvSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseEntity))]
    public partial class RealSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Classs_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_SelectForSortOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_SelectForPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_SelectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_SelectsForSortOperationCompleted;
        
        private System.Threading.SendOrPostCallback Classs_SelectsForPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_SelectForSortOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_SelectForPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_SelectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_SelectsForSortOperationCompleted;
        
        private System.Threading.SendOrPostCallback Student_SelectsForPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_SelectForSortOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_SelectForPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_SelectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_SelectsForSortOperationCompleted;
        
        private System.Threading.SendOrPostCallback StudentX_SelectsForPageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RealSrv() {
            this.Url = global::Test.NTest.Properties.Settings.Default.Test_NTest_Real_RealSrv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Classs_AddCompletedEventHandler Classs_AddCompleted;
        
        /// <remarks/>
        public event Classs_UpdateCompletedEventHandler Classs_UpdateCompleted;
        
        /// <remarks/>
        public event Classs_DeleteCompletedEventHandler Classs_DeleteCompleted;
        
        /// <remarks/>
        public event Classs_SelectCompletedEventHandler Classs_SelectCompleted;
        
        /// <remarks/>
        public event Classs_SelectForSortCompletedEventHandler Classs_SelectForSortCompleted;
        
        /// <remarks/>
        public event Classs_SelectForPageCompletedEventHandler Classs_SelectForPageCompleted;
        
        /// <remarks/>
        public event Classs_SelectsCompletedEventHandler Classs_SelectsCompleted;
        
        /// <remarks/>
        public event Classs_SelectsForSortCompletedEventHandler Classs_SelectsForSortCompleted;
        
        /// <remarks/>
        public event Classs_SelectsForPageCompletedEventHandler Classs_SelectsForPageCompleted;
        
        /// <remarks/>
        public event Student_AddCompletedEventHandler Student_AddCompleted;
        
        /// <remarks/>
        public event Student_UpdateCompletedEventHandler Student_UpdateCompleted;
        
        /// <remarks/>
        public event Student_DeleteCompletedEventHandler Student_DeleteCompleted;
        
        /// <remarks/>
        public event Student_SelectCompletedEventHandler Student_SelectCompleted;
        
        /// <remarks/>
        public event Student_SelectForSortCompletedEventHandler Student_SelectForSortCompleted;
        
        /// <remarks/>
        public event Student_SelectForPageCompletedEventHandler Student_SelectForPageCompleted;
        
        /// <remarks/>
        public event Student_SelectsCompletedEventHandler Student_SelectsCompleted;
        
        /// <remarks/>
        public event Student_SelectsForSortCompletedEventHandler Student_SelectsForSortCompleted;
        
        /// <remarks/>
        public event Student_SelectsForPageCompletedEventHandler Student_SelectsForPageCompleted;
        
        /// <remarks/>
        public event StudentX_AddCompletedEventHandler StudentX_AddCompleted;
        
        /// <remarks/>
        public event StudentX_UpdateCompletedEventHandler StudentX_UpdateCompleted;
        
        /// <remarks/>
        public event StudentX_DeleteCompletedEventHandler StudentX_DeleteCompleted;
        
        /// <remarks/>
        public event StudentX_SelectCompletedEventHandler StudentX_SelectCompleted;
        
        /// <remarks/>
        public event StudentX_SelectForSortCompletedEventHandler StudentX_SelectForSortCompleted;
        
        /// <remarks/>
        public event StudentX_SelectForPageCompletedEventHandler StudentX_SelectForPageCompleted;
        
        /// <remarks/>
        public event StudentX_SelectsCompletedEventHandler StudentX_SelectsCompleted;
        
        /// <remarks/>
        public event StudentX_SelectsForSortCompletedEventHandler StudentX_SelectsForSortCompleted;
        
        /// <remarks/>
        public event StudentX_SelectsForPageCompletedEventHandler StudentX_SelectsForPageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Classs_Add(ClasssInfo o) {
            object[] results = this.Invoke("Classs_Add", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Classs_AddAsync(ClasssInfo o) {
            this.Classs_AddAsync(o, null);
        }
        
        /// <remarks/>
        public void Classs_AddAsync(ClasssInfo o, object userState) {
            if ((this.Classs_AddOperationCompleted == null)) {
                this.Classs_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_AddOperationCompleted);
            }
            this.InvokeAsync("Classs_Add", new object[] {
                        o}, this.Classs_AddOperationCompleted, userState);
        }
        
        private void OnClasss_AddOperationCompleted(object arg) {
            if ((this.Classs_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_AddCompleted(this, new Classs_AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Classs_Update(ClasssInfo o) {
            object[] results = this.Invoke("Classs_Update", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Classs_UpdateAsync(ClasssInfo o) {
            this.Classs_UpdateAsync(o, null);
        }
        
        /// <remarks/>
        public void Classs_UpdateAsync(ClasssInfo o, object userState) {
            if ((this.Classs_UpdateOperationCompleted == null)) {
                this.Classs_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_UpdateOperationCompleted);
            }
            this.InvokeAsync("Classs_Update", new object[] {
                        o}, this.Classs_UpdateOperationCompleted, userState);
        }
        
        private void OnClasss_UpdateOperationCompleted(object arg) {
            if ((this.Classs_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_UpdateCompleted(this, new Classs_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Classs_Delete(string o) {
            object[] results = this.Invoke("Classs_Delete", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Classs_DeleteAsync(string o) {
            this.Classs_DeleteAsync(o, null);
        }
        
        /// <remarks/>
        public void Classs_DeleteAsync(string o, object userState) {
            if ((this.Classs_DeleteOperationCompleted == null)) {
                this.Classs_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_DeleteOperationCompleted);
            }
            this.InvokeAsync("Classs_Delete", new object[] {
                        o}, this.Classs_DeleteOperationCompleted, userState);
        }
        
        private void OnClasss_DeleteOperationCompleted(object arg) {
            if ((this.Classs_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_DeleteCompleted(this, new Classs_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClasssInfo[] Classs_Select(ClasssInfo entity) {
            object[] results = this.Invoke("Classs_Select", new object[] {
                        entity});
            return ((ClasssInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Classs_SelectAsync(ClasssInfo entity) {
            this.Classs_SelectAsync(entity, null);
        }
        
        /// <remarks/>
        public void Classs_SelectAsync(ClasssInfo entity, object userState) {
            if ((this.Classs_SelectOperationCompleted == null)) {
                this.Classs_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_SelectOperationCompleted);
            }
            this.InvokeAsync("Classs_Select", new object[] {
                        entity}, this.Classs_SelectOperationCompleted, userState);
        }
        
        private void OnClasss_SelectOperationCompleted(object arg) {
            if ((this.Classs_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_SelectCompleted(this, new Classs_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_SelectForSort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClasssInfo[] Classs_SelectForSort(ClasssInfo entity, string sortField, bool isDesc) {
            object[] results = this.Invoke("Classs_SelectForSort", new object[] {
                        entity,
                        sortField,
                        isDesc});
            return ((ClasssInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Classs_SelectForSortAsync(ClasssInfo entity, string sortField, bool isDesc) {
            this.Classs_SelectForSortAsync(entity, sortField, isDesc, null);
        }
        
        /// <remarks/>
        public void Classs_SelectForSortAsync(ClasssInfo entity, string sortField, bool isDesc, object userState) {
            if ((this.Classs_SelectForSortOperationCompleted == null)) {
                this.Classs_SelectForSortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_SelectForSortOperationCompleted);
            }
            this.InvokeAsync("Classs_SelectForSort", new object[] {
                        entity,
                        sortField,
                        isDesc}, this.Classs_SelectForSortOperationCompleted, userState);
        }
        
        private void OnClasss_SelectForSortOperationCompleted(object arg) {
            if ((this.Classs_SelectForSortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_SelectForSortCompleted(this, new Classs_SelectForSortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_SelectForPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClasssInfo[] Classs_SelectForPage(ClasssInfo entity, int Skip, int Count) {
            object[] results = this.Invoke("Classs_SelectForPage", new object[] {
                        entity,
                        Skip,
                        Count});
            return ((ClasssInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Classs_SelectForPageAsync(ClasssInfo entity, int Skip, int Count) {
            this.Classs_SelectForPageAsync(entity, Skip, Count, null);
        }
        
        /// <remarks/>
        public void Classs_SelectForPageAsync(ClasssInfo entity, int Skip, int Count, object userState) {
            if ((this.Classs_SelectForPageOperationCompleted == null)) {
                this.Classs_SelectForPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_SelectForPageOperationCompleted);
            }
            this.InvokeAsync("Classs_SelectForPage", new object[] {
                        entity,
                        Skip,
                        Count}, this.Classs_SelectForPageOperationCompleted, userState);
        }
        
        private void OnClasss_SelectForPageOperationCompleted(object arg) {
            if ((this.Classs_SelectForPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_SelectForPageCompleted(this, new Classs_SelectForPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_Selects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClasssInfo[] Classs_Selects() {
            object[] results = this.Invoke("Classs_Selects", new object[0]);
            return ((ClasssInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Classs_SelectsAsync() {
            this.Classs_SelectsAsync(null);
        }
        
        /// <remarks/>
        public void Classs_SelectsAsync(object userState) {
            if ((this.Classs_SelectsOperationCompleted == null)) {
                this.Classs_SelectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_SelectsOperationCompleted);
            }
            this.InvokeAsync("Classs_Selects", new object[0], this.Classs_SelectsOperationCompleted, userState);
        }
        
        private void OnClasss_SelectsOperationCompleted(object arg) {
            if ((this.Classs_SelectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_SelectsCompleted(this, new Classs_SelectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_SelectsForSort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClasssInfo[] Classs_SelectsForSort(string sortField, bool isDesc) {
            object[] results = this.Invoke("Classs_SelectsForSort", new object[] {
                        sortField,
                        isDesc});
            return ((ClasssInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Classs_SelectsForSortAsync(string sortField, bool isDesc) {
            this.Classs_SelectsForSortAsync(sortField, isDesc, null);
        }
        
        /// <remarks/>
        public void Classs_SelectsForSortAsync(string sortField, bool isDesc, object userState) {
            if ((this.Classs_SelectsForSortOperationCompleted == null)) {
                this.Classs_SelectsForSortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_SelectsForSortOperationCompleted);
            }
            this.InvokeAsync("Classs_SelectsForSort", new object[] {
                        sortField,
                        isDesc}, this.Classs_SelectsForSortOperationCompleted, userState);
        }
        
        private void OnClasss_SelectsForSortOperationCompleted(object arg) {
            if ((this.Classs_SelectsForSortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_SelectsForSortCompleted(this, new Classs_SelectsForSortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Classs_SelectsForPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClasssInfo[] Classs_SelectsForPage(int Skip, int Count) {
            object[] results = this.Invoke("Classs_SelectsForPage", new object[] {
                        Skip,
                        Count});
            return ((ClasssInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Classs_SelectsForPageAsync(int Skip, int Count) {
            this.Classs_SelectsForPageAsync(Skip, Count, null);
        }
        
        /// <remarks/>
        public void Classs_SelectsForPageAsync(int Skip, int Count, object userState) {
            if ((this.Classs_SelectsForPageOperationCompleted == null)) {
                this.Classs_SelectsForPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClasss_SelectsForPageOperationCompleted);
            }
            this.InvokeAsync("Classs_SelectsForPage", new object[] {
                        Skip,
                        Count}, this.Classs_SelectsForPageOperationCompleted, userState);
        }
        
        private void OnClasss_SelectsForPageOperationCompleted(object arg) {
            if ((this.Classs_SelectsForPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Classs_SelectsForPageCompleted(this, new Classs_SelectsForPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Student_Add(StudentInfo o) {
            object[] results = this.Invoke("Student_Add", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Student_AddAsync(StudentInfo o) {
            this.Student_AddAsync(o, null);
        }
        
        /// <remarks/>
        public void Student_AddAsync(StudentInfo o, object userState) {
            if ((this.Student_AddOperationCompleted == null)) {
                this.Student_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_AddOperationCompleted);
            }
            this.InvokeAsync("Student_Add", new object[] {
                        o}, this.Student_AddOperationCompleted, userState);
        }
        
        private void OnStudent_AddOperationCompleted(object arg) {
            if ((this.Student_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_AddCompleted(this, new Student_AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Student_Update(StudentInfo o) {
            object[] results = this.Invoke("Student_Update", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Student_UpdateAsync(StudentInfo o) {
            this.Student_UpdateAsync(o, null);
        }
        
        /// <remarks/>
        public void Student_UpdateAsync(StudentInfo o, object userState) {
            if ((this.Student_UpdateOperationCompleted == null)) {
                this.Student_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_UpdateOperationCompleted);
            }
            this.InvokeAsync("Student_Update", new object[] {
                        o}, this.Student_UpdateOperationCompleted, userState);
        }
        
        private void OnStudent_UpdateOperationCompleted(object arg) {
            if ((this.Student_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_UpdateCompleted(this, new Student_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Student_Delete(string o) {
            object[] results = this.Invoke("Student_Delete", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Student_DeleteAsync(string o) {
            this.Student_DeleteAsync(o, null);
        }
        
        /// <remarks/>
        public void Student_DeleteAsync(string o, object userState) {
            if ((this.Student_DeleteOperationCompleted == null)) {
                this.Student_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_DeleteOperationCompleted);
            }
            this.InvokeAsync("Student_Delete", new object[] {
                        o}, this.Student_DeleteOperationCompleted, userState);
        }
        
        private void OnStudent_DeleteOperationCompleted(object arg) {
            if ((this.Student_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_DeleteCompleted(this, new Student_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentInfo[] Student_Select(StudentInfo entity) {
            object[] results = this.Invoke("Student_Select", new object[] {
                        entity});
            return ((StudentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Student_SelectAsync(StudentInfo entity) {
            this.Student_SelectAsync(entity, null);
        }
        
        /// <remarks/>
        public void Student_SelectAsync(StudentInfo entity, object userState) {
            if ((this.Student_SelectOperationCompleted == null)) {
                this.Student_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_SelectOperationCompleted);
            }
            this.InvokeAsync("Student_Select", new object[] {
                        entity}, this.Student_SelectOperationCompleted, userState);
        }
        
        private void OnStudent_SelectOperationCompleted(object arg) {
            if ((this.Student_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_SelectCompleted(this, new Student_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_SelectForSort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentInfo[] Student_SelectForSort(StudentInfo entity, string sortField, bool isDesc) {
            object[] results = this.Invoke("Student_SelectForSort", new object[] {
                        entity,
                        sortField,
                        isDesc});
            return ((StudentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Student_SelectForSortAsync(StudentInfo entity, string sortField, bool isDesc) {
            this.Student_SelectForSortAsync(entity, sortField, isDesc, null);
        }
        
        /// <remarks/>
        public void Student_SelectForSortAsync(StudentInfo entity, string sortField, bool isDesc, object userState) {
            if ((this.Student_SelectForSortOperationCompleted == null)) {
                this.Student_SelectForSortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_SelectForSortOperationCompleted);
            }
            this.InvokeAsync("Student_SelectForSort", new object[] {
                        entity,
                        sortField,
                        isDesc}, this.Student_SelectForSortOperationCompleted, userState);
        }
        
        private void OnStudent_SelectForSortOperationCompleted(object arg) {
            if ((this.Student_SelectForSortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_SelectForSortCompleted(this, new Student_SelectForSortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_SelectForPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentInfo[] Student_SelectForPage(StudentInfo entity, int Skip, int Count) {
            object[] results = this.Invoke("Student_SelectForPage", new object[] {
                        entity,
                        Skip,
                        Count});
            return ((StudentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Student_SelectForPageAsync(StudentInfo entity, int Skip, int Count) {
            this.Student_SelectForPageAsync(entity, Skip, Count, null);
        }
        
        /// <remarks/>
        public void Student_SelectForPageAsync(StudentInfo entity, int Skip, int Count, object userState) {
            if ((this.Student_SelectForPageOperationCompleted == null)) {
                this.Student_SelectForPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_SelectForPageOperationCompleted);
            }
            this.InvokeAsync("Student_SelectForPage", new object[] {
                        entity,
                        Skip,
                        Count}, this.Student_SelectForPageOperationCompleted, userState);
        }
        
        private void OnStudent_SelectForPageOperationCompleted(object arg) {
            if ((this.Student_SelectForPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_SelectForPageCompleted(this, new Student_SelectForPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_Selects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentInfo[] Student_Selects() {
            object[] results = this.Invoke("Student_Selects", new object[0]);
            return ((StudentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Student_SelectsAsync() {
            this.Student_SelectsAsync(null);
        }
        
        /// <remarks/>
        public void Student_SelectsAsync(object userState) {
            if ((this.Student_SelectsOperationCompleted == null)) {
                this.Student_SelectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_SelectsOperationCompleted);
            }
            this.InvokeAsync("Student_Selects", new object[0], this.Student_SelectsOperationCompleted, userState);
        }
        
        private void OnStudent_SelectsOperationCompleted(object arg) {
            if ((this.Student_SelectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_SelectsCompleted(this, new Student_SelectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_SelectsForSort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentInfo[] Student_SelectsForSort(string sortField, bool isDesc) {
            object[] results = this.Invoke("Student_SelectsForSort", new object[] {
                        sortField,
                        isDesc});
            return ((StudentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Student_SelectsForSortAsync(string sortField, bool isDesc) {
            this.Student_SelectsForSortAsync(sortField, isDesc, null);
        }
        
        /// <remarks/>
        public void Student_SelectsForSortAsync(string sortField, bool isDesc, object userState) {
            if ((this.Student_SelectsForSortOperationCompleted == null)) {
                this.Student_SelectsForSortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_SelectsForSortOperationCompleted);
            }
            this.InvokeAsync("Student_SelectsForSort", new object[] {
                        sortField,
                        isDesc}, this.Student_SelectsForSortOperationCompleted, userState);
        }
        
        private void OnStudent_SelectsForSortOperationCompleted(object arg) {
            if ((this.Student_SelectsForSortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_SelectsForSortCompleted(this, new Student_SelectsForSortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Student_SelectsForPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentInfo[] Student_SelectsForPage(int Skip, int Count) {
            object[] results = this.Invoke("Student_SelectsForPage", new object[] {
                        Skip,
                        Count});
            return ((StudentInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void Student_SelectsForPageAsync(int Skip, int Count) {
            this.Student_SelectsForPageAsync(Skip, Count, null);
        }
        
        /// <remarks/>
        public void Student_SelectsForPageAsync(int Skip, int Count, object userState) {
            if ((this.Student_SelectsForPageOperationCompleted == null)) {
                this.Student_SelectsForPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudent_SelectsForPageOperationCompleted);
            }
            this.InvokeAsync("Student_SelectsForPage", new object[] {
                        Skip,
                        Count}, this.Student_SelectsForPageOperationCompleted, userState);
        }
        
        private void OnStudent_SelectsForPageOperationCompleted(object arg) {
            if ((this.Student_SelectsForPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Student_SelectsForPageCompleted(this, new Student_SelectsForPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool StudentX_Add(StudentXInfo o) {
            object[] results = this.Invoke("StudentX_Add", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_AddAsync(StudentXInfo o) {
            this.StudentX_AddAsync(o, null);
        }
        
        /// <remarks/>
        public void StudentX_AddAsync(StudentXInfo o, object userState) {
            if ((this.StudentX_AddOperationCompleted == null)) {
                this.StudentX_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_AddOperationCompleted);
            }
            this.InvokeAsync("StudentX_Add", new object[] {
                        o}, this.StudentX_AddOperationCompleted, userState);
        }
        
        private void OnStudentX_AddOperationCompleted(object arg) {
            if ((this.StudentX_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_AddCompleted(this, new StudentX_AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_Update", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool StudentX_Update(StudentXInfo o) {
            object[] results = this.Invoke("StudentX_Update", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_UpdateAsync(StudentXInfo o) {
            this.StudentX_UpdateAsync(o, null);
        }
        
        /// <remarks/>
        public void StudentX_UpdateAsync(StudentXInfo o, object userState) {
            if ((this.StudentX_UpdateOperationCompleted == null)) {
                this.StudentX_UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_UpdateOperationCompleted);
            }
            this.InvokeAsync("StudentX_Update", new object[] {
                        o}, this.StudentX_UpdateOperationCompleted, userState);
        }
        
        private void OnStudentX_UpdateOperationCompleted(object arg) {
            if ((this.StudentX_UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_UpdateCompleted(this, new StudentX_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool StudentX_Delete(string o) {
            object[] results = this.Invoke("StudentX_Delete", new object[] {
                        o});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_DeleteAsync(string o) {
            this.StudentX_DeleteAsync(o, null);
        }
        
        /// <remarks/>
        public void StudentX_DeleteAsync(string o, object userState) {
            if ((this.StudentX_DeleteOperationCompleted == null)) {
                this.StudentX_DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_DeleteOperationCompleted);
            }
            this.InvokeAsync("StudentX_Delete", new object[] {
                        o}, this.StudentX_DeleteOperationCompleted, userState);
        }
        
        private void OnStudentX_DeleteOperationCompleted(object arg) {
            if ((this.StudentX_DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_DeleteCompleted(this, new StudentX_DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentXInfo[] StudentX_Select(StudentXInfo entity) {
            object[] results = this.Invoke("StudentX_Select", new object[] {
                        entity});
            return ((StudentXInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_SelectAsync(StudentXInfo entity) {
            this.StudentX_SelectAsync(entity, null);
        }
        
        /// <remarks/>
        public void StudentX_SelectAsync(StudentXInfo entity, object userState) {
            if ((this.StudentX_SelectOperationCompleted == null)) {
                this.StudentX_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_SelectOperationCompleted);
            }
            this.InvokeAsync("StudentX_Select", new object[] {
                        entity}, this.StudentX_SelectOperationCompleted, userState);
        }
        
        private void OnStudentX_SelectOperationCompleted(object arg) {
            if ((this.StudentX_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_SelectCompleted(this, new StudentX_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_SelectForSort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentXInfo[] StudentX_SelectForSort(StudentXInfo entity, string sortField, bool isDesc) {
            object[] results = this.Invoke("StudentX_SelectForSort", new object[] {
                        entity,
                        sortField,
                        isDesc});
            return ((StudentXInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_SelectForSortAsync(StudentXInfo entity, string sortField, bool isDesc) {
            this.StudentX_SelectForSortAsync(entity, sortField, isDesc, null);
        }
        
        /// <remarks/>
        public void StudentX_SelectForSortAsync(StudentXInfo entity, string sortField, bool isDesc, object userState) {
            if ((this.StudentX_SelectForSortOperationCompleted == null)) {
                this.StudentX_SelectForSortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_SelectForSortOperationCompleted);
            }
            this.InvokeAsync("StudentX_SelectForSort", new object[] {
                        entity,
                        sortField,
                        isDesc}, this.StudentX_SelectForSortOperationCompleted, userState);
        }
        
        private void OnStudentX_SelectForSortOperationCompleted(object arg) {
            if ((this.StudentX_SelectForSortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_SelectForSortCompleted(this, new StudentX_SelectForSortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_SelectForPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentXInfo[] StudentX_SelectForPage(StudentXInfo entity, int Skip, int Count) {
            object[] results = this.Invoke("StudentX_SelectForPage", new object[] {
                        entity,
                        Skip,
                        Count});
            return ((StudentXInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_SelectForPageAsync(StudentXInfo entity, int Skip, int Count) {
            this.StudentX_SelectForPageAsync(entity, Skip, Count, null);
        }
        
        /// <remarks/>
        public void StudentX_SelectForPageAsync(StudentXInfo entity, int Skip, int Count, object userState) {
            if ((this.StudentX_SelectForPageOperationCompleted == null)) {
                this.StudentX_SelectForPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_SelectForPageOperationCompleted);
            }
            this.InvokeAsync("StudentX_SelectForPage", new object[] {
                        entity,
                        Skip,
                        Count}, this.StudentX_SelectForPageOperationCompleted, userState);
        }
        
        private void OnStudentX_SelectForPageOperationCompleted(object arg) {
            if ((this.StudentX_SelectForPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_SelectForPageCompleted(this, new StudentX_SelectForPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_Selects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentXInfo[] StudentX_Selects() {
            object[] results = this.Invoke("StudentX_Selects", new object[0]);
            return ((StudentXInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_SelectsAsync() {
            this.StudentX_SelectsAsync(null);
        }
        
        /// <remarks/>
        public void StudentX_SelectsAsync(object userState) {
            if ((this.StudentX_SelectsOperationCompleted == null)) {
                this.StudentX_SelectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_SelectsOperationCompleted);
            }
            this.InvokeAsync("StudentX_Selects", new object[0], this.StudentX_SelectsOperationCompleted, userState);
        }
        
        private void OnStudentX_SelectsOperationCompleted(object arg) {
            if ((this.StudentX_SelectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_SelectsCompleted(this, new StudentX_SelectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_SelectsForSort", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentXInfo[] StudentX_SelectsForSort(string sortField, bool isDesc) {
            object[] results = this.Invoke("StudentX_SelectsForSort", new object[] {
                        sortField,
                        isDesc});
            return ((StudentXInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_SelectsForSortAsync(string sortField, bool isDesc) {
            this.StudentX_SelectsForSortAsync(sortField, isDesc, null);
        }
        
        /// <remarks/>
        public void StudentX_SelectsForSortAsync(string sortField, bool isDesc, object userState) {
            if ((this.StudentX_SelectsForSortOperationCompleted == null)) {
                this.StudentX_SelectsForSortOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_SelectsForSortOperationCompleted);
            }
            this.InvokeAsync("StudentX_SelectsForSort", new object[] {
                        sortField,
                        isDesc}, this.StudentX_SelectsForSortOperationCompleted, userState);
        }
        
        private void OnStudentX_SelectsForSortOperationCompleted(object arg) {
            if ((this.StudentX_SelectsForSortCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_SelectsForSortCompleted(this, new StudentX_SelectsForSortCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentX_SelectsForPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentXInfo[] StudentX_SelectsForPage(int Skip, int Count) {
            object[] results = this.Invoke("StudentX_SelectsForPage", new object[] {
                        Skip,
                        Count});
            return ((StudentXInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void StudentX_SelectsForPageAsync(int Skip, int Count) {
            this.StudentX_SelectsForPageAsync(Skip, Count, null);
        }
        
        /// <remarks/>
        public void StudentX_SelectsForPageAsync(int Skip, int Count, object userState) {
            if ((this.StudentX_SelectsForPageOperationCompleted == null)) {
                this.StudentX_SelectsForPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentX_SelectsForPageOperationCompleted);
            }
            this.InvokeAsync("StudentX_SelectsForPage", new object[] {
                        Skip,
                        Count}, this.StudentX_SelectsForPageOperationCompleted, userState);
        }
        
        private void OnStudentX_SelectsForPageOperationCompleted(object arg) {
            if ((this.StudentX_SelectsForPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentX_SelectsForPageCompleted(this, new StudentX_SelectsForPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClasssInfo : BaseEntity {
        
        private int idField;
        
        private string nameField;
        
        private System.Nullable<int> studentField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Student {
            get {
                return this.studentField;
            }
            set {
                this.studentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentXInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StudentInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClasssInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseEntity {
        
        private string sortFieldField;
        
        private bool isDescField;
        
        /// <remarks/>
        public string SortField {
            get {
                return this.sortFieldField;
            }
            set {
                this.sortFieldField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentXInfo : BaseEntity {
        
        private int idField;
        
        private string nameField;
        
        private System.Nullable<int> ageField;
        
        private string sexField;
        
        private string classField;
        
        private string flagField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StudentInfo : BaseEntity {
        
        private int idField;
        
        private string nameField;
        
        private System.Nullable<int> ageField;
        
        private string sexField;
        
        private string classField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_AddCompletedEventHandler(object sender, Classs_AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_UpdateCompletedEventHandler(object sender, Classs_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_DeleteCompletedEventHandler(object sender, Classs_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_SelectCompletedEventHandler(object sender, Classs_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClasssInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClasssInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_SelectForSortCompletedEventHandler(object sender, Classs_SelectForSortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_SelectForSortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_SelectForSortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClasssInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClasssInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_SelectForPageCompletedEventHandler(object sender, Classs_SelectForPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_SelectForPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_SelectForPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClasssInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClasssInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_SelectsCompletedEventHandler(object sender, Classs_SelectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_SelectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_SelectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClasssInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClasssInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_SelectsForSortCompletedEventHandler(object sender, Classs_SelectsForSortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_SelectsForSortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_SelectsForSortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClasssInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClasssInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Classs_SelectsForPageCompletedEventHandler(object sender, Classs_SelectsForPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Classs_SelectsForPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Classs_SelectsForPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClasssInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClasssInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_AddCompletedEventHandler(object sender, Student_AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_UpdateCompletedEventHandler(object sender, Student_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_DeleteCompletedEventHandler(object sender, Student_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_SelectCompletedEventHandler(object sender, Student_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_SelectForSortCompletedEventHandler(object sender, Student_SelectForSortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_SelectForSortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_SelectForSortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_SelectForPageCompletedEventHandler(object sender, Student_SelectForPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_SelectForPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_SelectForPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_SelectsCompletedEventHandler(object sender, Student_SelectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_SelectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_SelectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_SelectsForSortCompletedEventHandler(object sender, Student_SelectsForSortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_SelectsForSortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_SelectsForSortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Student_SelectsForPageCompletedEventHandler(object sender, Student_SelectsForPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Student_SelectsForPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Student_SelectsForPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_AddCompletedEventHandler(object sender, StudentX_AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_UpdateCompletedEventHandler(object sender, StudentX_UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_DeleteCompletedEventHandler(object sender, StudentX_DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_SelectCompletedEventHandler(object sender, StudentX_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentXInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentXInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_SelectForSortCompletedEventHandler(object sender, StudentX_SelectForSortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_SelectForSortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_SelectForSortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentXInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentXInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_SelectForPageCompletedEventHandler(object sender, StudentX_SelectForPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_SelectForPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_SelectForPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentXInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentXInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_SelectsCompletedEventHandler(object sender, StudentX_SelectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_SelectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_SelectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentXInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentXInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_SelectsForSortCompletedEventHandler(object sender, StudentX_SelectsForSortCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_SelectsForSortCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_SelectsForSortCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentXInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentXInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StudentX_SelectsForPageCompletedEventHandler(object sender, StudentX_SelectsForPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentX_SelectsForPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentX_SelectsForPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentXInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentXInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591